#! /bin/sh -f
#export RASPA_DIR=${HOME}/RASPA2/
export RASPA_DIR=${HOME}/RASPA/simulations
export DYLD_LIBRARY_PATH=${RASPA_DIR}/lib
export LD_LIBRARY_PATH=${RASPA_DIR}/lib
$RASPA_DIR/bin/simulate $1

cp read_data.sh ./Output/System_0/read_data.sh
cp plot.gpl     ./Output/System_0/plot.gpl
cp plot.gpl     ./Output/System_0/plot_log.gpl
cd ./Output/System_0
./read_data.sh
./plot.gpl
./plot_log.gpl
cd ./../../
cp ./Output/System_0/plot.png ./
cp ./Output/System_0/plot_log.png ./
